### ISSUE TITLE
resources_rc.py missing in the repo

### ISSUE THREAD

**Issue by ipesanz** [jrenken/qgis-PosiView#6]
Hello,

I tried to download and make the application but it seems the resources_rc.py file does not exist in the repo.

**Output:**
```
~/tests/qgis-PosiView-master$ make deploy
pyrcc5 -o resources_rc.py  resources.qrc
make: pyrcc5: Command not found
Makefile:113: recipe for target 'resources_rc.py' failed
make: *** [resources_rc.py] Error 127
```

**Comment by jrenken** [comment]
Hi Isaac,
resources_rc.py is created by pyrcc5 during make. But pyrcc5 is not found.
You have to install pyqt5-dev-tools (Ubuntu).
